### ISSUE TITLE
Using a pretrained model?

### ISSUE THREAD

**Issue by fabge** [earthspecies/sperm_whale_bioacoustics#1]
In the notebook [05_Clan_and_coda_type_detection_with_RNN](https://github.com/earthspecies/sperm_whale_bioacoustics/blob/master/05_Clan_and_coda_type_detection_with_RNN.ipynb) a pretrained model should be used and is instantiated like so:

```
learn = Learner(
    dls,
    model_pretrain.Model(),
    metrics=[accuracy_multi],
    loss_func=BCEWithLogitsLossFlat()
)
```

How are the weights from the pretrained model loaded? As far as I can see, only the architecture is used with `model_pretrain.Model()`, without any pretrained weights or am I missing something?

**Comment by radekosmulski** [comment]
Hi Fabian! Thank you very much for looking at the code and being on the lookout for potential issues, appreciate it.

At the top of the notebook, I train with preloading the weights:
![image](https://user-images.githubusercontent.com/2444926/77410868-e5352a00-6dbb-11ea-9771-955d866521fd.png)

Later on, I run an experiment as you note with only recreating the architecture, but not loading the pretrained weights. I still get the same result.

I reworded the text a little bit so hoping the narrative will work better now. But if you do see something off or there is still something that is not clear here, please let me know!

Thank you again for looking at this and for your comment!

**Comment by fabge** [comment]
Oh I see! I probably got the with and without pretrained part mixed up due to the "Does pretraining help?" heading. 
Thank you for clarifying and improving the text and for doing what you do 😄!
